In [1]:
import tensorflow as tf

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import pandas as pd
df = pd.read_csv("/content/drive/My Drive/gllab/bank.csv")

In [7]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
# Drop the columns which are unique for all users like IDs (5 points)

In [0]:
df = df.drop(["RowNumber","CustomerId","Surname"], axis=1)

In [0]:
#Distinguish the feature and target set (5 points)
X = df.drop("Exited", axis=1)
y = df["Exited"]

In [10]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
X['Geography'] = labelencoder_x.fit_transform(X['Geography'])
X['Gender'] = labelencoder_x.fit_transform(X['Gender'])
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [0]:
#Divide the data set into Train and test sets
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split(X,y,test_size=0.3,random_state=42)

In [0]:
#Normalize the train and test data (5 points)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)
test_x = sc.transform(test_x)

In [0]:
#Initialize & build the model (10 points)

In [15]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [16]:
tf.keras.backend.clear_session()
model = Sequential()
model.add(Dense(activation = 'relu', input_dim = 10, units=6, kernel_initializer='uniform'))
model.add(Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 
model.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform')) 
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3657: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [17]:
model.fit(train_x, train_y, batch_size=10, epochs=100)

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1020: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3005: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Epoch 1/100
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

7000/7000 [==============================] - 2s 215us/step - loss: 0.5063 - acc: 0.7920
Epoch 2/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.4256 - acc: 0.8017
Epoch 3/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.4032 - acc: 0.8119
Epoch 4/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3817 - acc: 0.8414
Epoch 5/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.3690 - acc: 0.8511
Epoch 6/100
7000/7000 [==============================] - 1s 120us/step - loss: 0.3627 - acc: 0.8521
Epoch 7/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3590 - acc: 0.8543
Epoch 8/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3567 - acc: 0.8536
Epoch 9/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3555 - acc: 0.8537
Epoch 10/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3548 - acc: 0.8539
Epoch 11/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3543 - acc: 0.8537
Epoch 12/100
7000/7000 [==============================] - 1s 120us/step - loss: 0.3532 - acc: 0.8553
Epoch 13/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3527 - acc: 0.8544
Epoch 14/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3530 - acc: 0.8564
Epoch 15/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3526 - acc: 0.8544
Epoch 16/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3518 - acc: 0.8553
Epoch 17/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3513 - acc: 0.8550
Epoch 18/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3510 - acc: 0.8551
Epoch 19/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3510 - acc: 0.8549
Epoch 20/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3501 - acc: 0.8557
Epoch 21/100
7000/7000 [==============================] - 1s 120us/step - loss: 0.3490 - acc: 0.8559
Epoch 22/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3496 - acc: 0.8563
Epoch 23/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3491 - acc: 0.8567
Epoch 24/100
7000/7000 [==============================] - 1s 117us/step - loss: 0.3487 - acc: 0.8554
Epoch 25/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3482 - acc: 0.8559
Epoch 26/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3481 - acc: 0.8580
Epoch 27/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3483 - acc: 0.8579
Epoch 28/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3476 - acc: 0.8567
Epoch 29/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3471 - acc: 0.8580
Epoch 30/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3477 - acc: 0.8564
Epoch 31/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3475 - acc: 0.8584
Epoch 32/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3473 - acc: 0.8556
Epoch 33/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3470 - acc: 0.8573
Epoch 34/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3462 - acc: 0.8589
Epoch 35/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3468 - acc: 0.8580
Epoch 36/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3467 - acc: 0.8587
Epoch 37/100
7000/7000 [==============================] - 1s 118us/step - loss: 0.3471 - acc: 0.8569
Epoch 38/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3461 - acc: 0.8579
Epoch 39/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3463 - acc: 0.8579
Epoch 40/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3462 - acc: 0.8573
Epoch 41/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.3458 - acc: 0.8586
Epoch 42/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3455 - acc: 0.8593
Epoch 43/100
7000/7000 [==============================] - 1s 117us/step - loss: 0.3459 - acc: 0.8569
Epoch 44/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3451 - acc: 0.8573
Epoch 45/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3457 - acc: 0.8571
Epoch 46/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3458 - acc: 0.8606
Epoch 47/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3450 - acc: 0.8589
Epoch 48/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3449 - acc: 0.8603
Epoch 49/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3450 - acc: 0.8580
Epoch 50/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3448 - acc: 0.8586
Epoch 51/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3458 - acc: 0.8589
Epoch 52/100
7000/7000 [==============================] - 1s 118us/step - loss: 0.3451 - acc: 0.8591
Epoch 53/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3453 - acc: 0.8583
Epoch 54/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3451 - acc: 0.8583
Epoch 55/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3449 - acc: 0.8593
Epoch 56/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3451 - acc: 0.8589
Epoch 57/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3447 - acc: 0.8591
Epoch 58/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3451 - acc: 0.8574
Epoch 59/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3447 - acc: 0.8584
Epoch 60/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3454 - acc: 0.8597
Epoch 61/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3448 - acc: 0.8590
Epoch 62/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3452 - acc: 0.8603
Epoch 63/100
7000/7000 [==============================] - 1s 122us/step - loss: 0.3447 - acc: 0.8577
Epoch 64/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3448 - acc: 0.8600
Epoch 65/100
7000/7000 [==============================] - 1s 123us/step - loss: 0.3448 - acc: 0.8601
Epoch 66/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3448 - acc: 0.8600
Epoch 67/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3454 - acc: 0.8580
Epoch 68/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3445 - acc: 0.8591
Epoch 69/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3441 - acc: 0.8581
Epoch 70/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.3441 - acc: 0.8589
Epoch 71/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3443 - acc: 0.8597
Epoch 72/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3445 - acc: 0.8580
Epoch 73/100
7000/7000 [==============================] - 1s 114us/step - loss: 0.3447 - acc: 0.8591
Epoch 74/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3445 - acc: 0.8604
Epoch 75/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3440 - acc: 0.8600
Epoch 76/100
7000/7000 [==============================] - 1s 116us/step - loss: 0.3442 - acc: 0.8581
Epoch 77/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3436 - acc: 0.8599
Epoch 78/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3441 - acc: 0.8584
Epoch 79/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3440 - acc: 0.8584
Epoch 80/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3438 - acc: 0.8579
Epoch 81/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3444 - acc: 0.8581
Epoch 82/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3443 - acc: 0.8596
Epoch 83/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3431 - acc: 0.8589
Epoch 84/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3439 - acc: 0.8591
Epoch 85/100
7000/7000 [==============================] - 1s 118us/step - loss: 0.3438 - acc: 0.8587
Epoch 86/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3440 - acc: 0.8597
Epoch 87/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.3442 - acc: 0.8584
Epoch 88/100
7000/7000 [==============================] - 1s 115us/step - loss: 0.3443 - acc: 0.8614
Epoch 89/100
7000/7000 [==============================] - 1s 118us/step - loss: 0.3439 - acc: 0.8574
Epoch 90/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3439 - acc: 0.8600
Epoch 91/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3435 - acc: 0.8607
Epoch 92/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3436 - acc: 0.8579
Epoch 93/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3436 - acc: 0.8591
Epoch 94/100
7000/7000 [==============================] - 1s 111us/step - loss: 0.3432 - acc: 0.8596
Epoch 95/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.3427 - acc: 0.8596
Epoch 96/100
7000/7000 [==============================] - 1s 107us/step - loss: 0.3440 - acc: 0.8604
Epoch 97/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3430 - acc: 0.8594
Epoch 98/100
7000/7000 [==============================] - 1s 113us/step - loss: 0.3428 - acc: 0.8577
Epoch 99/100
7000/7000 [==============================] - 1s 112us/step - loss: 0.3434 - acc: 0.8603
Epoch 100/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3427 - acc: 0.8583

In [0]:
#Print the Accuracy score and confusion matrix (5 points)
y_pred = model.predict(test_x)

In [19]:
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]

In [20]:
from sklearn.metrics import confusion_matrix, roc_auc_score
cm = confusion_matrix(test_y, y_pred)
print(cm)

[[2335   81]
 [ 327  257]]

In [21]:
roc = roc_auc_score(test_y,y_pred)
print(roc)

0.7032710015422299